import { randomUUID } from "node:crypto";
import { ApprovedRuleSchema, DeployRuleResultSchema, RegisteredRuleSchema, RuleSchema, ScopeSchema, type BCAdapter, type RegisteredRule, type Scope } from "@drivacy/shared";
import { AppError } from "../errors/app-error.js";
import { toRuleVersionNumber } from "../rule/rule-service.js";
import type { ChainScopeDeploymentRow, EvaluationScopeRow, RegistrationTargetRow, RuleRegistrationRepository } from "./rule-registration-repository.js";

const kstDate = (value: Date | string): string => {
  const date = value instanceof Date ? value : new Date(value); if (Number.isNaN(date.valueOf())) throw new AppError("INTERNAL_SERVER_ERROR", "Stored scope date is invalid", 500);
  const p = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Seoul", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date);
  const part=(type:string)=>p.find(x=>x.type===type)?.value; return `${part("year")}-${part("month")}-${part("day")}`;
};
export class RuleRegistrationService {
  public constructor(private readonly repo: RuleRegistrationRepository, private readonly adapter: BCAdapter) {}
  private scope(target: RegistrationTargetRow, stored: EvaluationScopeRow): Scope { return ScopeSchema.parse({ applicantId:stored.ownerUserId,contractId:stored.insuranceContractId,insurerId:target.insurerId,endorsementId:stored.specialContractId,evaluationPeriod:{id:stored.evaluationPeriodId,startDate:stored.evaluationStartsOn,endDate:stored.evaluationEndsOn} }); }
  private async getScope(target: RegistrationTargetRow): Promise<EvaluationScopeRow> { const found=await this.repo.findScope(target.ownerUserId,target.insuranceContractId,target.specialContractId); if(found)return found; if(!target.selectedAt)throw new AppError("SPECIAL_CONTRACT_NOT_SELECTED","Special contract is not selected",409); const start=kstDate(target.selectedAt),end=kstDate(target.coverageEndsAt); if(start>end)throw new AppError("INVALID_EVALUATION_PERIOD","Special contract selection is after coverage end",409);
    // 평가 Scope는 Rule version이 아닌 최초 특약 선택일부터 보험 종료일까지의 누적 범위다.
    return this.repo.createScope({ownerUserId:target.ownerUserId,insuranceContractId:target.insuranceContractId,specialContractId:target.specialContractId,evaluationPeriodId:randomUUID(),evaluationStartsOn:start,evaluationEndsOn:end}); }
  private approved(target: RegistrationTargetRow) { if(target.status!=="APPROVED")throw new AppError("RULE_NOT_APPROVED","Only approved rule versions can be registered",409); const rule=RuleSchema.safeParse({id:target.ruleId,version:toRuleVersionNumber(target.version),insurerId:target.insurerId,endorsementId:target.specialContractId,...(target.ruleDefinition as object)}); if(!rule.success)throw new AppError("INTERNAL_SERVER_ERROR","Stored rule data is invalid",500); return ApprovedRuleSchema.parse({approval:"approved",rule:rule.data}); }
  private registered(input: unknown, target: RegistrationTargetRow, deployment?: ChainScopeDeploymentRow): RegisteredRule { const parsed=RegisteredRuleSchema.safeParse(input);if(!parsed.success)throw new AppError("CHAIN_REGISTRATION_INVALID","Chain adapter returned invalid registration",502);const value=parsed.data,rule=value.rule; if(rule.id!==target.ruleId||rule.version!==toRuleVersionNumber(target.version)||rule.insurerId!==target.insurerId||rule.endorsementId!==target.specialContractId||value.registration!=="chain-confirmed"||(deployment&&value.chainContractAddress!==deployment.chainContractAddress))throw new AppError("CHAIN_REGISTRATION_MISMATCH","Chain adapter registration does not match the requested rule",502);return value; }
  public async register(user: string, special: string, version: number): Promise<RegisteredRule> { const target=await this.repo.findTarget(user,special,version); if(!target)throw new AppError("SPECIAL_CONTRACT_NOT_FOUND","Special contract or rule version was not found",404); const approved=this.approved(target); const scopeRow=await this.getScope(target); const existing=await this.repo.findRegistrationByScopeAndVersion(scopeRow.id,target.ruleVersionId); if(existing){ const ds=await this.repo.findDeployments(scopeRow.id);const d=ds.find(x=>x.id===existing.chainScopeDeploymentId);if(!d)throw new AppError("INTERNAL_SERVER_ERROR","Stored deployment is missing",500);return RegisteredRuleSchema.parse({...approved,registration:"chain-confirmed",ruleHash:existing.ruleHash,adapterProfile:d.adapterProfile,network:d.network,chainContractAddress:d.chainContractAddress,registrationTransactionId:existing.registrationTransactionId}); }
    const scope=this.scope(target,scopeRow); const deployments=await this.repo.findDeployments(scopeRow.id); if(deployments.length>1)throw new AppError("CHAIN_DEPLOYMENT_AMBIGUOUS","More than one chain deployment exists for this scope",409);
    if(deployments.length===0){ const result=DeployRuleResultSchema.safeParse(await this.adapter.deployRule({scope,approvedRule:approved}));if(!result.success)throw new AppError("CHAIN_REGISTRATION_INVALID","Chain adapter returned invalid deployment",502); const registered=this.registered(result.data.registeredRule,target);await this.repo.createDeploymentAndRegistration({evaluationScopeId:scopeRow.id,adapterProfile:registered.adapterProfile,network:registered.network,chainContractAddress:registered.chainContractAddress,deploymentTransactionId:result.data.deploymentTransactionId},{ruleVersionId:target.ruleVersionId,ruleHash:registered.ruleHash,registrationTransactionId:registered.registrationTransactionId});return registered; }
    const deployment=deployments[0]; const registered=this.registered(await this.adapter.updateRule({scope,deployment:{network:deployment.network,adapterProfile:deployment.adapterProfile,chainContractAddress:deployment.chainContractAddress},approvedRule:approved}),target,deployment); await this.repo.createRegistration({chainScopeDeploymentId:deployment.id,ruleVersionId:target.ruleVersionId,ruleHash:registered.ruleHash,registrationTransactionId:registered.registrationTransactionId});return registered; }
}
