export const RULE_DRAFT_ISSUE_CODES = [
  "EMPTY_INPUT",
  "INPUT_TOO_LONG",
  "EXTRACTION_FAILED",
  "UNVERIFIED_EXTRACTION",
  "NO_SUPPORTED_FIELDS",
  "MISSING_FIELDS",
  "PROVIDER_UNAVAILABLE",
  "PROVIDER_TIMEOUT",
  "PDF_NO_TEXT",
  "PDF_TOO_LARGE",
] as const;

export type RuleDraftIssueCode = (typeof RULE_DRAFT_ISSUE_CODES)[number];
