import { describe, expect, it } from "vitest";
import type { AdapterRuntime, ConfirmedState, Trip } from "@drivacy/shared";
import { DrivingService } from "../src/driving/driving-service.js";
import type { DrivingRepository, DrivingSessionRow, DrivingTarget } from "../src/driving/driving-repository.js";

const ids={user:"11111111-1111-4111-8111-111111111111",contract:"22222222-2222-4222-8222-222222222222",special:"33333333-3333-4333-8333-333333333333",scope:"44444444-4444-4444-8444-444444444444",version:"55555555-5555-4555-8555-555555555555",session:"66666666-6666-4666-8666-666666666666"};
const runtime:AdapterRuntime={network:"local",adapterProfile:"test"};
const confirmed:ConfirmedState={kind:"confirmed",state:{scope:{applicantId:ids.user,contractId:ids.contract,insurerId:"insurer",endorsementId:ids.special,evaluationPeriod:{id:"period",startDate:"2026-01-01",endDate:"2026-12-31"}},rule:{id:"rule",version:1,ruleHash:"rule-hash"},version:0,tripCount:0,totals:{distanceM:0,durationSeconds:0,speedingCount:0,accelerationCount:0,brakingCount:0},score:100,conditionsMet:false,expectedDiscountBps:0,datasetRoot:"empty",stateSalt:"0".repeat(64),stateCommitment:"state-commitment"},confirmation:{execution:"live",network:"local",adapterProfile:"test",chainContractAddress:"contract-address",transactionId:"genesis-tx",blockId:"block",operationId:"genesis",previousStateCommitment:"0".repeat(64),newStateCommitment:"state-commitment",ruleHash:"rule-hash",datasetRoot:"empty",observedAt:"2026-01-01T00:00:00.000Z"}};
class MemoryRepo implements DrivingRepository { public rows:DrivingSessionRow[]=[];public generated=0;public target:DrivingTarget={scopeId:ids.scope,evaluationPeriodId:"period",ruleVersionId:ids.version,ruleVersion:"1",ruleStatus:"APPROVED",ruleId:"rule",insurerId:"insurer",specialContractId:ids.special,ruleHash:"rule-hash",chainContractAddress:"contract-address",ruleDefinition:{formula:"cumulative-event-deduction-v1",initialScore:100,speedingPenalty:2,accelerationPenalty:1,brakingPenalty:3,minimumDistanceM:500000,minimumScore:80,premiumMinimumScore:90,baseDiscountBps:1000,premiumDiscountBps:1200}};public trip?:Trip;
 async findTarget(){return this.target;} async findByKey(_:string,key:string){return this.rows.find(x=>x.idempotencyKey===key);} async hasSession(){return this.rows.length>0;} async createSession(s:Omit<DrivingSessionRow,"id"|"endedAt"|"status">,trip:Trip){this.generated++;const existing=await this.findByKey(s.evaluationScopeId,s.idempotencyKey);if(existing)return existing;const row:DrivingSessionRow={id:ids.session,evaluationScopeId:s.evaluationScopeId,ruleVersionId:s.ruleVersionId,tripId:s.tripId,datasetSalt:s.datasetSalt,idempotencyKey:s.idempotencyKey,status:"GENERATED",startedAt:new Date("2026-01-01T00:00:00Z"),endedAt:null};this.trip=trip;this.rows.push(row);return row;} async findOwned(id:string,user:string){return user===ids.user?this.rows.find(x=>x.id===id):undefined;} async endOwned(id:string,user:string){const r=await this.findOwned(id,user);if(!r)return; r.status="ENDED";r.endedAt=new Date("2026-01-01T01:00:00Z");return r;} async records(){return this.trip!.records;}
}
const request={insuranceContractId:ids.contract,specialContractId:ids.special,evaluationPeriod:"period"};
describe("DrivingService",()=>{it("reuses the same generated trip for an idempotency key and ends idempotently",async()=>{const repo=new MemoryRepo();const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>confirmed},{next:()=>0.5});const first=await service.start(ids.user,request,"key");const repeated=await service.start(ids.user,request,"key");expect(repeated).toEqual(first);expect(repo.generated).toBe(1);expect(first.ruleVersionId).toBeUndefined();const ended=await service.end(first.sessionId,ids.user);expect(ended.status).toBe("ENDED");expect((await service.end(first.sessionId,ids.user)).endedAt).toBe(ended.endedAt);});it("rejects a scope without a current registered Rule",async()=>{const repo=new MemoryRepo();repo.target.ruleVersionId=null;const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>undefined});await expect(service.start(ids.user,request,"key")).rejects.toMatchObject({code:"RULE_NOT_REGISTERED"});});it("requires a confirmed Genesis even for the first session",async()=>{const repo=new MemoryRepo();const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>undefined});await expect(service.start(ids.user,request,"key")).rejects.toMatchObject({code:"CONFIRMED_STATE_UNAVAILABLE"});expect(repo.generated).toBe(0);});it("does not start another session while Genesis is still the latest confirmed state",async()=>{const repo=new MemoryRepo();const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>confirmed},{next:()=>0.5});await service.start(ids.user,request,"first");await expect(service.start(ids.user,request,"second")).rejects.toMatchObject({code:"CONFIRMED_STATE_UNAVAILABLE"});expect(repo.generated).toBe(1);});});

describe("DrivingService Genesis attack cases",()=>{
  it.each([
    ["another network",{confirmation:{...confirmed.confirmation,network:"preprod" as const}}],
    ["another contract",{confirmation:{...confirmed.confirmation,chainContractAddress:"other"}}],
    ["another Rule",{state:{...confirmed.state,rule:{...confirmed.state.rule,ruleHash:"other"}}}],
    ["another owner",{state:{...confirmed.state,scope:{...confirmed.state.scope,applicantId:"other"}}}],
  ])("rejects %s before making a session",async(_,change)=>{const repo=new MemoryRepo();const candidate={...confirmed,...change} as ConfirmedState;const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>candidate},{next:()=>0.5});await expect(service.start(ids.user,request,"key")).rejects.toMatchObject({code:"CONFIRMED_STATE_UNAVAILABLE"});expect(repo.generated).toBe(0);});
  it("rejects a Genesis labelled version zero with nonzero accumulated distance",async()=>{const repo=new MemoryRepo();const candidate:ConfirmedState={...confirmed,state:{...confirmed.state,totals:{...confirmed.state.totals,distanceM:300000}}};const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>candidate},{next:()=>0.5});await expect(service.start(ids.user,request,"key")).rejects.toMatchObject({code:"CONFIRMED_STATE_UNAVAILABLE"});expect(repo.generated).toBe(0);});
  it("rejects a Genesis labelled version zero with a nonzero trip count",async()=>{const repo=new MemoryRepo();const candidate:ConfirmedState={...confirmed,state:{...confirmed.state,tripCount:1}};const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>candidate},{next:()=>0.5});await expect(service.start(ids.user,request,"key")).rejects.toMatchObject({code:"CONFIRMED_STATE_UNAVAILABLE"});expect(repo.generated).toBe(0);});
  it("rejects a Genesis labelled version zero with a nonzero event counter",async()=>{const repo=new MemoryRepo();const candidate:ConfirmedState={...confirmed,state:{...confirmed.state,totals:{...confirmed.state.totals,speedingCount:1}}};const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>candidate},{next:()=>0.5});await expect(service.start(ids.user,request,"key")).rejects.toMatchObject({code:"CONFIRMED_STATE_UNAVAILABLE"});expect(repo.generated).toBe(0);});
  it("rejects an inconsistent confirmed revision after Genesis",async()=>{const repo=new MemoryRepo();const candidate:ConfirmedState={...confirmed,state:{...confirmed.state,version:1,tripCount:0}};const service=new DrivingService(repo,runtime,{getConfirmedState:async()=>candidate},{next:()=>0.5});await expect(service.start(ids.user,request,"key")).rejects.toMatchObject({code:"CONFIRMED_STATE_UNAVAILABLE"});expect(repo.generated).toBe(0);});
});
