import { describe, expect, it } from "vitest";
import type { BCAdapter, DeployRuleRequest, DeployRuleResult, RegisteredRule, UpdateRuleRequest } from "@drivacy/shared";
import { RuleRegistrationService } from "../src/rule-registration/rule-registration-service.js";
import type { ChainScopeDeploymentRow, EvaluationScopeRow, RegistrationTargetRow, RuleRegistrationRepository, RuleRegistrationRow } from "../src/rule-registration/rule-registration-repository.js";

const ids={ insurer:"11111111-1111-4111-8111-111111111111",owner:"22222222-2222-4222-8222-222222222222",contract:"33333333-3333-4333-8333-333333333333",special:"44444444-4444-4444-8444-444444444444",rule:"55555555-5555-4555-8555-555555555555",v1:"66666666-6666-4666-8666-666666666666",v2:"77777777-7777-4777-8777-777777777777" };
const definition={formula:"cumulative-event-deduction-v1" as const,initialScore:100 as const,speedingPenalty:2,accelerationPenalty:1,brakingPenalty:3,minimumDistanceM:500000,minimumScore:80,premiumMinimumScore:90,baseDiscountBps:1000,premiumDiscountBps:1200};
const target=(version="1",status:"DRAFT"|"APPROVED"="APPROVED"):RegistrationTargetRow=>({ownerUserId:ids.owner,insuranceContractId:ids.contract,insurerId:ids.insurer,specialContractId:ids.special,selectedAt:"2026-01-01T14:59:00.000Z",coverageEndsAt:"2026-12-31T15:00:00.000Z",ruleId:ids.rule,ruleVersionId:version==="1"?ids.v1:ids.v2,version,status,ruleDefinition:definition});
class MemoryRepo implements RuleRegistrationRepository {
  public targets=new Map<string,RegistrationTargetRow>(); public scopes:EvaluationScopeRow[]=[]; public deployments:ChainScopeDeploymentRow[]=[]; public registrations:RuleRegistrationRow[]=[]; private locks=new Map<string,Promise<void>>();
  public constructor(){this.targets.set("1",target("1"));this.targets.set("2",target("2"));}
  async findTarget(_:string, special:string, version:number){return special===ids.special?this.targets.get(String(version)):undefined;}
  async findScope(owner:string,contract:string,special:string){return this.scopes.find(x=>x.ownerUserId===owner&&x.insuranceContractId===contract&&x.specialContractId===special);}
  async createScope(x:Omit<EvaluationScopeRow,"id">){const current=this.scopes.find(v=>v.ownerUserId===x.ownerUserId&&v.insuranceContractId===x.insuranceContractId&&v.specialContractId===x.specialContractId);if(current)return current;const row={id:`scope-${this.scopes.length+1}`,...x};this.scopes.push(row);return row;}
  async findDeployment(scope:string,runtime:{network:"fixture"|"local"|"preprod";adapterProfile:string}){return this.deployments.find(x=>x.evaluationScopeId===scope&&x.network===runtime.network&&x.adapterProfile===runtime.adapterProfile);}
  async findRegistration(deployment:string,version:string){return this.registrations.find(x=>x.chainScopeDeploymentId===deployment&&x.ruleVersionId===version);}
  async withRegistrationLock<T>(scope:string,version:string,task:()=>Promise<T>):Promise<T>{const key=`${scope}:${version}`,previous=this.locks.get(key)??Promise.resolve();let release!:()=>void;const next=new Promise<void>(resolve=>{release=resolve;});this.locks.set(key,next);await previous;try{return await task();}finally{release();if(this.locks.get(key)===next)this.locks.delete(key);}}
  async createDeploymentAndRegistration(d:Omit<ChainScopeDeploymentRow,"id">,r:Omit<RuleRegistrationRow,"id"|"chainScopeDeploymentId">){const deployment={id:`deployment-${this.deployments.length+1}`,...d};this.deployments.push(deployment);const registration={id:`registration-${this.registrations.length+1}`,chainScopeDeploymentId:deployment.id,...r};this.registrations.push(registration);return{deployment,registration};}
  async createRegistration(r:Omit<RuleRegistrationRow,"id">){const existing=this.registrations.find(x=>x.chainScopeDeploymentId===r.chainScopeDeploymentId&&x.ruleVersionId===r.ruleVersionId);if(existing)return existing;const row={id:`registration-${this.registrations.length+1}`,...r};this.registrations.push(row);return row;}
}
class FakeAdapter implements BCAdapter {
  public deployCalls=0;public updateCalls=0;public bad=false; public mismatch=false;
  private registered(rule:DeployRuleRequest["approvedRule"], address:string, tx:string):RegisteredRule { const r=rule.rule;return {approval:"approved",rule:this.mismatch?{...r,version:r.version+1}:r,registration:"chain-confirmed",ruleHash:"fake-rule-hash",adapterProfile:"fake-adapter",network:"fixture",chainContractAddress:address,registrationTransactionId:tx}; }
  async deployRule(input:DeployRuleRequest):Promise<DeployRuleResult>{this.deployCalls++;if(this.bad)return {} as DeployRuleResult;return{deploymentTransactionId:"deploy-tx",registeredRule:this.registered(input.approvedRule,"fake-contract","registration-tx-1")};}
  async updateRule(input:UpdateRuleRequest):Promise<RegisteredRule>{this.updateCalls++;if(this.bad)return {} as RegisteredRule;return this.registered(input.approvedRule,this.mismatch?"wrong-contract":input.deployment.chainContractAddress,"registration-tx-2");}
  async calculateTrip(){throw new Error("not used");} async processTrip(){throw new Error("not used");} async getTripStatus(){throw new Error("not used");}
}
const setup=()=>{const repo=new MemoryRepo(),adapter=new FakeAdapter();return{repo,adapter,service:new RuleRegistrationService(repo,adapter,{network:"fixture",adapterProfile:"fake-adapter"})};};
describe("RuleRegistrationService",()=>{
  it("deploys an approved v1 with a KST selection-to-coverage scope",async()=>{const {repo,adapter,service}=setup();const result=await service.register(ids.insurer,ids.special,1);expect(adapter.deployCalls).toBe(1);expect(result.chainContractAddress).toBe("fake-contract");expect(repo.scopes[0]).toMatchObject({evaluationStartsOn:"2026-01-01",evaluationEndsOn:"2027-01-01"});expect(repo.deployments).toHaveLength(1);expect(repo.registrations).toHaveLength(1);});
  it("does not call the adapter again for the same scope and version",async()=>{const {adapter,service}=setup();await service.register(ids.insurer,ids.special,1);await service.register(ids.insurer,ids.special,1);expect(adapter.deployCalls).toBe(1);expect(adapter.updateCalls).toBe(0);});
  it("updates v2 on the existing deployment without replacing v1 history",async()=>{const {repo,adapter,service}=setup();await service.register(ids.insurer,ids.special,1);await service.register(ids.insurer,ids.special,2);expect(adapter.updateCalls).toBe(1);expect(repo.scopes).toHaveLength(1);expect(repo.deployments).toHaveLength(1);expect(repo.registrations).toHaveLength(2);});
  it("rejects a DRAFT version before chain work",async()=>{const {repo,adapter,service}=setup();repo.targets.set("1",target("1","DRAFT"));await expect(service.register(ids.insurer,ids.special,1)).rejects.toMatchObject({code:"RULE_NOT_APPROVED"});expect(adapter.deployCalls).toBe(0);});
  it("requires the selected special contract and a valid period",async()=>{const {repo,service}=setup();repo.targets.set("1",{...target(),selectedAt:null});await expect(service.register(ids.insurer,ids.special,1)).rejects.toMatchObject({code:"SPECIAL_CONTRACT_NOT_SELECTED"});repo.targets.set("1",{...target(),selectedAt:"2027-01-01T15:00:00.000Z"});await expect(service.register(ids.insurer,ids.special,1)).rejects.toMatchObject({code:"INVALID_EVALUATION_PERIOD"});});
  it("rejects an unauthorized special contract",async()=>{const {service}=setup();await expect(service.register(ids.insurer,"88888888-8888-4888-8888-888888888888",1)).rejects.toMatchObject({code:"SPECIAL_CONTRACT_NOT_FOUND"});});
  it("rejects malformed adapter results and mismatched deployment addresses",async()=>{const first=setup();first.adapter.bad=true;await expect(first.service.register(ids.insurer,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_INVALID"});const second=setup();await second.service.register(ids.insurer,ids.special,1);second.adapter.mismatch=true;await expect(second.service.register(ids.insurer,ids.special,2)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_MISMATCH"});expect(second.repo.registrations).toHaveLength(1);});
  it("keeps the first scope period ID and dates when v2 is registered",async()=>{const {repo,service}=setup();await service.register(ids.insurer,ids.special,1);const first={...repo.scopes[0]};await service.register(ids.insurer,ids.special,2);expect(repo.scopes).toEqual([first]);});
  it("rejects malformed stored Rule data before calling the adapter",async()=>{const {repo,adapter,service}=setup();repo.targets.set("1",{...target(),ruleDefinition:{}});await expect(service.register(ids.insurer,ids.special,1)).rejects.toMatchObject({code:"INTERNAL_SERVER_ERROR"});expect(adapter.deployCalls).toBe(0);});
  it("selects only the current runtime deployment when others coexist",async()=>{const {repo,adapter,service}=setup();await service.register(ids.insurer,ids.special,1);repo.deployments.push({...repo.deployments[0],id:"deployment-2",network:"local",adapterProfile:"other"});await service.register(ids.insurer,ids.special,2);expect(adapter.updateCalls).toBe(1);expect(repo.registrations).toHaveLength(2);});
  it.each([["0"],["4294967296"],["abc"]])("rejects invalid stored bigint version %s",async(version)=>{const {repo,service}=setup();repo.targets.set("1",{...target(),version});await expect(service.register(ids.insurer,ids.special,1)).rejects.toMatchObject({code:"INTERNAL_SERVER_ERROR"});});
  it("accepts the maximum uint32 stored bigint version",async()=>{const {repo,adapter,service}=setup();repo.targets.clear();repo.targets.set("4294967295",{...target("4294967295"),ruleVersionId:ids.v1});await service.register(ids.insurer,ids.special,4294967295);expect(adapter.deployCalls).toBe(1);});
  it("does not persist deployment or registration after a deploy failure",async()=>{const {repo,adapter,service}=setup();adapter.bad=true;await expect(service.register(ids.insurer,ids.special,1)).rejects.toBeDefined();expect(repo.deployments).toHaveLength(0);expect(repo.registrations).toHaveLength(0);});
  it("serializes concurrent v1 deployment before the adapter",async()=>{const {repo,adapter,service}=setup();await Promise.all([service.register(ids.insurer,ids.special,1),service.register(ids.insurer,ids.special,1)]);expect(adapter.deployCalls).toBe(1);expect(repo.registrations).toHaveLength(1);});
  it("serializes concurrent v2 updates before the adapter",async()=>{const {repo,adapter,service}=setup();await service.register(ids.insurer,ids.special,1);await Promise.all([service.register(ids.insurer,ids.special,2),service.register(ids.insurer,ids.special,2)]);expect(adapter.updateCalls).toBe(1);expect(repo.registrations).toHaveLength(2);});
});
