import { describe, expect, it } from "vitest";
import type { BCAdapter, ConfirmedState, DeployRuleRequest, DeployRuleResult, InitialRegistrationStatus, RegisteredRule, Scope, UpdateRuleRequest } from "@drivacy/shared";
import { RuleRegistrationService } from "../src/rule-registration/rule-registration-service.js";
import type { ChainScopeDeploymentRow, EvaluationScopeRow, RegistrationTargetRow, RuleRegistrationRepository, RuleRegistrationRow } from "../src/rule-registration/rule-registration-repository.js";

const ids={ insurer:"11111111-1111-4111-8111-111111111111",owner:"22222222-2222-4222-8222-222222222222",contract:"33333333-3333-4333-8333-333333333333",special:"44444444-4444-4444-8444-444444444444",rule:"55555555-5555-4555-8555-555555555555",v1:"66666666-6666-4666-8666-666666666666",v2:"77777777-7777-4777-8777-777777777777",v3:"88888888-8888-4888-8888-888888888888" };
const definition={formula:"cumulative-event-deduction-v1" as const,initialScore:100 as const,speedingPenalty:2,accelerationPenalty:1,brakingPenalty:3,minimumDistanceM:500000,minimumScore:80,premiumMinimumScore:90,baseDiscountBps:1000,premiumDiscountBps:1200};
const driver={id:ids.owner,role:"DRIVER" as const},insurer={id:ids.insurer,role:"INSURER" as const};
const target=(version="1",status:"DRAFT"|"APPROVED"="APPROVED"):RegistrationTargetRow=>({ownerUserId:ids.owner,insuranceContractId:ids.contract,insurerId:ids.insurer,specialContractId:ids.special,selectedAt:"2026-01-01T14:59:00.000Z",coverageEndsAt:"2026-12-31T15:00:00.000Z",ruleId:ids.rule,ruleVersionId:version==="1"?ids.v1:version==="2"?ids.v2:ids.v3,version,status,ruleDefinition:definition});
class MemoryRepo implements RuleRegistrationRepository {
  public targets=new Map<string,RegistrationTargetRow>(); public scopes:EvaluationScopeRow[]=[]; public deployments:ChainScopeDeploymentRow[]=[]; public registrations:RuleRegistrationRow[]=[]; public confirmedGenesis:ConfirmedState|undefined; public failInitialPersistence=false;
  public attempts=new Map<string,{operationId:string;ruleVersionId:string;status:"pending"|"db-confirmed"}>(); private locks=new Map<string,Promise<void>>();
  public constructor(){this.targets.set("1",target("1"));this.targets.set("2",target("2"));this.targets.set("3",target("3"));}
  async findTarget(user:string, role:"DRIVER"|"INSURER", special:string, version:number){return special===ids.special&&((role==="DRIVER"&&user===ids.owner)||(role==="INSURER"&&user===ids.insurer))?this.targets.get(String(version)):undefined;}
  async findScope(owner:string,contract:string,special:string){return this.scopes.find(x=>x.ownerUserId===owner&&x.insuranceContractId===contract&&x.specialContractId===special);}
  async createScope(x:Omit<EvaluationScopeRow,"id">){const current=this.scopes.find(v=>v.ownerUserId===x.ownerUserId&&v.insuranceContractId===x.insuranceContractId&&v.specialContractId===x.specialContractId);if(current)return current;const row={id:`scope-${this.scopes.length+1}`,...x};this.scopes.push(row);return row;}
  async findDeployment(scope:string,runtime:{network:"fixture"|"local"|"preprod";adapterProfile:string}){return this.deployments.find(x=>x.evaluationScopeId===scope&&x.network===runtime.network&&x.adapterProfile===runtime.adapterProfile);}
  async findRegistration(deployment:string,version:string){return this.registrations.find(x=>x.chainScopeDeploymentId===deployment&&x.ruleVersionId===version);}
  async findConfirmedState(scope:Scope){return this.confirmedGenesis && JSON.stringify(this.confirmedGenesis.state.scope)===JSON.stringify(scope) ? this.confirmedGenesis : undefined;}
  async reserveInitialAttempt(scopeId:string,ruleVersionId:string,runtime:{network:string;adapterProfile:string}){const key=`${scopeId}:${runtime.network}:${runtime.adapterProfile}`,prior=this.attempts.get(key);if(prior)return{operationId:prior.operationId,ruleVersionId:prior.ruleVersionId,created:false};const operationId=`attempt-${this.attempts.size+1}`;this.attempts.set(key,{operationId,ruleVersionId,status:"pending"});return{operationId,ruleVersionId,created:true};}
  async withRegistrationLock<T>(scope:string,runtime:{network:string;adapterProfile:string},task:()=>Promise<T>):Promise<T>{const key=`${scope}:${runtime.network}:${runtime.adapterProfile}`,previous=this.locks.get(key)??Promise.resolve();let release!:()=>void;const next=new Promise<void>(resolve=>{release=resolve;});this.locks.set(key,next);await previous;try{return await task();}finally{release();if(this.locks.get(key)===next)this.locks.delete(key);}}
  async createInitialRegistration(operationId:string,d:Omit<ChainScopeDeploymentRow,"id"|"currentRuleVersionId"|"currentRuleVersion">,r:Omit<RuleRegistrationRow,"id"|"chainScopeDeploymentId">,_registered:RegisteredRule,genesis:ConfirmedState){if(this.failInitialPersistence)throw new Error("DB_WRITE_FAILED");const attempt=[...this.attempts.values()].find(a=>a.operationId===operationId);if(!attempt||attempt.ruleVersionId!==r.ruleVersionId)throw new Error("ATTEMPT_MISMATCH");const deployment={id:`deployment-${this.deployments.length+1}`,...d,currentRuleVersionId:r.ruleVersionId,currentRuleVersion:this.versionFor(r.ruleVersionId)};this.deployments.push(deployment);const registration={id:`registration-${this.registrations.length+1}`,chainScopeDeploymentId:deployment.id,...r};this.registrations.push(registration);this.confirmedGenesis=genesis;attempt.status="db-confirmed";}
  async createRegistrationAndSetCurrent(r:Omit<RuleRegistrationRow,"id">){const existing=this.registrations.find(x=>x.chainScopeDeploymentId===r.chainScopeDeploymentId&&x.ruleVersionId===r.ruleVersionId);if(existing)return existing;const row={id:`registration-${this.registrations.length+1}`,...r};this.registrations.push(row);const deployment=this.deployments.find(x=>x.id===r.chainScopeDeploymentId)!;deployment.currentRuleVersionId=r.ruleVersionId;deployment.currentRuleVersion=this.versionFor(r.ruleVersionId);return row;}
  private versionFor(id:string){return [...this.targets.values()].find(x=>x.ruleVersionId===id)?.version??null;}
}
class FakeAdapter implements BCAdapter {
  public deployCalls=0;public updateCalls=0;public bad=false; public mismatch=false; public alteredFormula=false; public deployOperationIds:string[]=[];
  public statusMode:"pending"|"not-submitted"|"chain-confirmed"|"wrong-operation"="pending";public lastDeployResult:DeployRuleResult|undefined;
  public genesisOverride:((value:ConfirmedState)=>ConfirmedState)|undefined; public omitGenesis=false;
  private registered(rule:DeployRuleRequest["approvedRule"], address:string, tx:string):RegisteredRule { const r=rule.rule;return {approval:"approved",rule:this.mismatch?{...r,version:r.version+1}:this.alteredFormula?{...r,speedingPenalty:r.speedingPenalty+1}:r,registration:"chain-confirmed",ruleHash:"fake-rule-hash",adapterProfile:"fake-adapter",network:"local",chainContractAddress:address,registrationTransactionId:tx}; }
  async deployRule(input:DeployRuleRequest):Promise<DeployRuleResult>{this.deployCalls++;this.deployOperationIds.push(input.operationId);if(this.bad)return {} as DeployRuleResult;
    const registeredRule=this.registered(input.approvedRule,"fake-contract","registration-tx-1");
    const state={scope:input.scope,rule:{id:registeredRule.rule.id,version:registeredRule.rule.version,ruleHash:registeredRule.ruleHash},
      version:0,tripCount:0,totals:{distanceM:0,durationSeconds:0,speedingCount:0,accelerationCount:0,brakingCount:0},
      score:100,conditionsMet:false,expectedDiscountBps:0,datasetRoot:"fake-empty-root",stateSalt:"11".repeat(32),stateCommitment:"fake-genesis-commitment"};
    const confirmedGenesis:ConfirmedState={kind:"confirmed",state,confirmation:{execution:"live",network:"local",adapterProfile:"fake-adapter",chainContractAddress:"fake-contract",transactionId:"initialize-tx",blockId:"fake-block",operationId:"genesis-initialize",previousStateCommitment:"0".repeat(64),newStateCommitment:state.stateCommitment,ruleHash:registeredRule.ruleHash,datasetRoot:state.datasetRoot,observedAt:"2026-09-21T00:00:00Z"}};
    if(this.omitGenesis)return {operationId:input.operationId,deploymentTransactionId:"deploy-tx",registeredRule} as DeployRuleResult;
    const result={operationId:input.operationId,deploymentTransactionId:"deploy-tx",registeredRule,confirmedGenesis:this.genesisOverride?.(confirmedGenesis)??confirmedGenesis};this.lastDeployResult=result;return result;}
  async getInitialRegistrationStatus(operationId:string):Promise<InitialRegistrationStatus>{if(this.statusMode==="chain-confirmed")return{operationId,status:"chain-confirmed",result:this.lastDeployResult!};return{operationId:this.statusMode==="wrong-operation"?"different-operation":operationId,status:this.statusMode==="not-submitted"?"not-submitted":"pending"};}
  async updateRule(input:UpdateRuleRequest):Promise<RegisteredRule>{this.updateCalls++;if(this.bad)return {} as RegisteredRule;return this.registered(input.approvedRule,this.mismatch?"wrong-contract":input.deployment.chainContractAddress,"registration-tx-2");}
  async calculateTrip(){throw new Error("not used");} async processTrip(){throw new Error("not used");} async getTripStatus(){throw new Error("not used");}
}
const setup=()=>{const repo=new MemoryRepo(),adapter=new FakeAdapter();return{repo,adapter,service:new RuleRegistrationService(repo,adapter,{network:"local",adapterProfile:"fake-adapter"})};};
describe("RuleRegistrationService",()=>{
  it("deploys an approved v1 with a KST selection-to-coverage scope and confirmed Genesis",async()=>{const {repo,adapter,service}=setup();const result=await service.register(driver,ids.special,1);expect(adapter.deployCalls).toBe(1);expect(result.chainContractAddress).toBe("fake-contract");expect(repo.scopes[0]).toMatchObject({evaluationStartsOn:"2026-01-01",evaluationEndsOn:"2027-01-01"});expect(repo.deployments).toHaveLength(1);expect(repo.registrations).toHaveLength(1);expect(repo.confirmedGenesis?.state).toMatchObject({version:0,tripCount:0,score:100});});
  it("does not call the adapter again for the same scope and version",async()=>{const {adapter,service}=setup();await service.register(driver,ids.special,1);await service.register(driver,ids.special,1);expect(adapter.deployCalls).toBe(1);expect(adapter.updateCalls).toBe(0);});
  it("does not report an existing registration as ready if its confirmed State is absent",async()=>{const {repo,adapter,service}=setup();await service.register(driver,ids.special,1);repo.confirmedGenesis=undefined;await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_STATE_NOT_CONFIRMED"});expect(adapter.deployCalls).toBe(1);});
  it("rejects a later Rule version until C supplies a confirmed Rule/State transition",async()=>{const {repo,adapter,service}=setup();await service.register(driver,ids.special,1);await expect(service.register(insurer,ids.special,2)).rejects.toMatchObject({code:"RULE_UPDATE_STATE_MIGRATION_REQUIRED"});expect(adapter.updateCalls).toBe(0);expect(repo.scopes).toHaveLength(1);expect(repo.deployments[0].currentRuleVersionId).toBe(ids.v1);expect(repo.registrations).toHaveLength(1);});
  it("still returns an already registered current Rule without attempting a state migration",async()=>{const {repo,service}=setup();await service.register(driver,ids.special,1);await expect(service.register(driver,ids.special,1)).resolves.toMatchObject({rule:{version:1}});expect(repo.deployments[0].currentRuleVersionId).toBe(ids.v1);});
  it("rejects a DRAFT version before chain work",async()=>{const {repo,adapter,service}=setup();repo.targets.set("1",target("1","DRAFT"));await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"RULE_NOT_APPROVED"});expect(adapter.deployCalls).toBe(0);});
  it("requires the selected special contract and a valid period",async()=>{const {repo,service}=setup();repo.targets.set("1",{...target(),selectedAt:null});await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"SPECIAL_CONTRACT_NOT_SELECTED"});repo.targets.set("1",{...target(),selectedAt:"2027-01-01T15:00:00.000Z"});await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"INVALID_EVALUATION_PERIOD"});});
  it("rejects an unauthorized special contract",async()=>{const {service}=setup();await expect(service.register(driver,"88888888-8888-4888-8888-888888888888",1)).rejects.toMatchObject({code:"SPECIAL_CONTRACT_NOT_FOUND"});});
  it("rejects malformed initial adapter results and blocks later updates before C",async()=>{const first=setup();first.adapter.bad=true;await expect(first.service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_INVALID"});const second=setup();await second.service.register(driver,ids.special,1);second.adapter.mismatch=true;await expect(second.service.register(insurer,ids.special,2)).rejects.toMatchObject({code:"RULE_UPDATE_STATE_MIGRATION_REQUIRED"});expect(second.adapter.updateCalls).toBe(0);expect(second.repo.registrations).toHaveLength(1);});
  it("keeps the first scope period ID and dates when a later Rule update is rejected",async()=>{const {repo,service}=setup();await service.register(driver,ids.special,1);const first={...repo.scopes[0]};await expect(service.register(insurer,ids.special,2)).rejects.toMatchObject({code:"RULE_UPDATE_STATE_MIGRATION_REQUIRED"});expect(repo.scopes).toEqual([first]);});
  it("rejects malformed stored Rule data before calling the adapter",async()=>{const {repo,adapter,service}=setup();repo.targets.set("1",{...target(),ruleDefinition:{}});await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"INTERNAL_SERVER_ERROR"});expect(adapter.deployCalls).toBe(0);});
  it("blocks the current runtime Rule update when another runtime deployment coexists",async()=>{const {repo,adapter,service}=setup();await service.register(driver,ids.special,1);repo.deployments.push({...repo.deployments[0],id:"deployment-2",network:"local",adapterProfile:"other"});await expect(service.register(insurer,ids.special,2)).rejects.toMatchObject({code:"RULE_UPDATE_STATE_MIGRATION_REQUIRED"});expect(adapter.updateCalls).toBe(0);expect(repo.registrations).toHaveLength(1);});
  it.each([["0"],["4294967296"],["abc"]])("rejects invalid stored bigint version %s",async(version)=>{const {repo,service}=setup();repo.targets.set("1",{...target(),version});await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"INTERNAL_SERVER_ERROR"});});
  it("accepts the maximum uint32 stored bigint version",async()=>{const {repo,adapter,service}=setup();repo.targets.clear();repo.targets.set("4294967295",{...target("4294967295"),ruleVersionId:ids.v1});await service.register(driver,ids.special,4294967295);expect(adapter.deployCalls).toBe(1);});
  it("does not persist deployment or registration after a deploy failure",async()=>{const {repo,adapter,service}=setup();adapter.bad=true;await expect(service.register(driver,ids.special,1)).rejects.toBeDefined();expect(repo.deployments).toHaveLength(0);expect(repo.registrations).toHaveLength(0);});
  it("does not redeploy after chain success but DB persistence fails",async()=>{const {repo,adapter,service}=setup();repo.failInitialPersistence=true;await expect(service.register(driver,ids.special,1)).rejects.toThrow("DB_WRITE_FAILED");expect(adapter.deployCalls).toBe(1);expect(repo.deployments).toHaveLength(0);expect([...repo.attempts.values()][0]?.status).toBe("pending");
    repo.failInitialPersistence=false;const restarted=new RuleRegistrationService(repo,adapter,{network:"local",adapterProfile:"fake-adapter"});await expect(restarted.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_UNRESOLVED"});expect(adapter.deployCalls).toBe(1);expect(repo.deployments).toHaveLength(0);});
  it("recovers a confirmed deployment after a DB failure without another deploy",async()=>{const {repo,adapter,service}=setup();repo.failInitialPersistence=true;await expect(service.register(driver,ids.special,1)).rejects.toThrow("DB_WRITE_FAILED");repo.failInitialPersistence=false;adapter.statusMode="chain-confirmed";const recovered=await new RuleRegistrationService(repo,adapter,{network:"local",adapterProfile:"fake-adapter"}).register(driver,ids.special,1);expect(recovered.chainContractAddress).toBe("fake-contract");expect(adapter.deployCalls).toBe(1);expect(repo.deployments).toHaveLength(1);expect([...repo.attempts.values()][0]?.status).toBe("db-confirmed");});
  it("rejects a recovered receipt bound to another subscriber",async()=>{const {repo,adapter,service}=setup();repo.failInitialPersistence=true;await expect(service.register(driver,ids.special,1)).rejects.toThrow("DB_WRITE_FAILED");repo.failInitialPersistence=false;adapter.statusMode="chain-confirmed";const result=adapter.lastDeployResult!;adapter.lastDeployResult={...result,confirmedGenesis:{...result.confirmedGenesis,state:{...result.confirmedGenesis.state,scope:{...result.confirmedGenesis.state.scope,applicantId:ids.v2}}}};await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_GENESIS_MISMATCH"});expect(adapter.deployCalls).toBe(1);expect(repo.deployments).toHaveLength(0);});
  it("rejects a recovered result from another operation",async()=>{const {repo,adapter,service}=setup();repo.failInitialPersistence=true;await expect(service.register(driver,ids.special,1)).rejects.toThrow("DB_WRITE_FAILED");repo.failInitialPersistence=false;adapter.statusMode="chain-confirmed";adapter.lastDeployResult={...adapter.lastDeployResult!,operationId:"other-operation"};await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_MISMATCH"});expect(adapter.deployCalls).toBe(1);expect(repo.deployments).toHaveLength(0);});
  it("retries the same operation only after C confirms it was not submitted",async()=>{const {repo,adapter,service}=setup();adapter.bad=true;await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_INVALID"});adapter.bad=false;adapter.statusMode="not-submitted";await service.register(driver,ids.special,1);expect(adapter.deployOperationIds).toEqual(["attempt-1","attempt-1"]);expect(repo.deployments).toHaveLength(1);});
  it("does not deploy when C status names a different operation",async()=>{const {adapter,service}=setup();adapter.bad=true;await expect(service.register(driver,ids.special,1)).rejects.toBeDefined();adapter.bad=false;adapter.statusMode="wrong-operation";await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_INVALID"});expect(adapter.deployCalls).toBe(1);});
  it("blocks another Rule version while the first deployment result is unresolved",async()=>{const {repo,adapter,service}=setup();adapter.omitGenesis=true;await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_INVALID"});await expect(service.register(driver,ids.special,2)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_UNRESOLVED"});expect(adapter.deployCalls).toBe(1);expect(adapter.deployOperationIds).toEqual(["attempt-1"]);expect([...repo.attempts.values()][0]?.ruleVersionId).toBe(ids.v1);});
  it("does not activate a deployed Rule without a confirmed Genesis",async()=>{const {repo,adapter,service}=setup();adapter.omitGenesis=true;await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_INVALID"});expect(repo.deployments).toHaveLength(0);expect(repo.registrations).toHaveLength(0);expect(repo.confirmedGenesis).toBeUndefined();});
  it.each([
    ["another scope",(g:ConfirmedState)=>({...g,state:{...g.state,scope:{...g.state.scope,applicantId:ids.v2}}})],
    ["another contract",(g:ConfirmedState)=>({...g,confirmation:{...g.confirmation,chainContractAddress:"other-contract"}})],
    ["a fixture receipt",(g:ConfirmedState)=>({...g,confirmation:{...g.confirmation,execution:"fixture" as const,network:"fixture" as const}})],
    ["nonzero genesis totals",(g:ConfirmedState)=>({...g,state:{...g.state,totals:{...g.state.totals,distanceM:1}}})],
    ["a claimed discount",(g:ConfirmedState)=>({...g,state:{...g.state,conditionsMet:true,expectedDiscountBps:1200}})],
    ["a nonzero previous commitment",(g:ConfirmedState)=>({...g,confirmation:{...g.confirmation,previousStateCommitment:"different"}})],
  ])("rejects %s before persisting Rule or State",async(_name,alter)=>{const {repo,adapter,service}=setup();adapter.genesisOverride=alter;await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_GENESIS_MISMATCH"});expect(repo.deployments).toHaveLength(0);expect(repo.registrations).toHaveLength(0);expect(repo.confirmedGenesis).toBeUndefined();});
  it("serializes concurrent v1 deployment before the adapter",async()=>{const {repo,adapter,service}=setup();await Promise.all([service.register(driver,ids.special,1),service.register(driver,ids.special,1)]);expect(adapter.deployCalls).toBe(1);expect(repo.registrations).toHaveLength(1);});
  it("rejects concurrent v2 updates before either can reach the adapter",async()=>{const {repo,adapter,service}=setup();await service.register(driver,ids.special,1);const attempts=await Promise.allSettled([service.register(insurer,ids.special,2),service.register(insurer,ids.special,2)]);expect(attempts.every(x=>x.status==="rejected")).toBe(true);expect(adapter.updateCalls).toBe(0);expect(repo.registrations).toHaveLength(1);});
  it("rejects an insurer's attempt to create the first subscriber contract",async()=>{const {repo,adapter,service}=setup();await expect(service.register(insurer,ids.special,1)).rejects.toMatchObject({code:"INITIAL_REGISTRATION_REQUIRED"});expect(repo.scopes).toHaveLength(0);expect(adapter.deployCalls).toBe(0);});
  it("rejects another driver and an unrelated insurer before adapter calls",async()=>{const {adapter,service}=setup();await expect(service.register({id:"99999999-9999-4999-8999-999999999999",role:"DRIVER"},ids.special,1)).rejects.toMatchObject({code:"SPECIAL_CONTRACT_NOT_FOUND"});await expect(service.register({id:"99999999-9999-4999-8999-999999999999",role:"INSURER"},ids.special,1)).rejects.toMatchObject({code:"SPECIAL_CONTRACT_NOT_FOUND"});expect(adapter.deployCalls).toBe(0);});
  it("rejects a driver's attempt to register an unregistered later rule",async()=>{const {repo,adapter,service}=setup();await service.register(driver,ids.special,1);await expect(service.register(driver,ids.special,2)).rejects.toMatchObject({code:"RULE_UPDATE_REQUIRES_INSURER"});expect(repo.registrations).toHaveLength(1);expect(adapter.updateCalls).toBe(0);});
  it("rejects an adapter result that changes approved coefficients",async()=>{const {repo,adapter,service}=setup();adapter.alteredFormula=true;await expect(service.register(driver,ids.special,1)).rejects.toMatchObject({code:"CHAIN_REGISTRATION_MISMATCH"});expect(repo.registrations).toHaveLength(0);});
  it("does not deploy two contracts for concurrent first registrations of different versions",async()=>{const {repo,adapter,service}=setup();const attempts=await Promise.allSettled([service.register(driver,ids.special,1),service.register(driver,ids.special,2)]);expect(attempts.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(adapter.deployCalls).toBe(1);expect(repo.deployments).toHaveLength(1);});
  it("does not call C with altered Rule coefficients when a Rule/State transition is unavailable",async()=>{const {repo,adapter,service}=setup();await service.register(driver,ids.special,1);adapter.alteredFormula=true;await expect(service.register(insurer,ids.special,2)).rejects.toMatchObject({code:"RULE_UPDATE_STATE_MIGRATION_REQUIRED"});expect(adapter.updateCalls).toBe(0);expect(repo.registrations).toHaveLength(1);expect(repo.deployments[0].currentRuleVersionId).toBe(ids.v1);});
  it("rejects a later Rule version before it can make the deployment point away from its Confirmed State",async()=>{const {repo,adapter,service}=setup();await service.register(driver,ids.special,1);await expect(service.register(insurer,ids.special,3)).rejects.toMatchObject({code:"RULE_UPDATE_STATE_MIGRATION_REQUIRED"});expect(repo.deployments[0].currentRuleVersionId).toBe(ids.v1);expect(adapter.updateCalls).toBe(0);});
});
