import { RuleDraftInputSchema, RuleResponseSchema, type RuleResponse } from "@drivacy/shared";
import { AppError } from "../errors/app-error.js";
import type { RuleRepository, RuleRow } from "./rule-repository.js";
const iso=(v:Date|null)=>v?.toISOString()??null;
export class RuleService { public constructor(private readonly repo:RuleRepository) {}
 private async rule(user:string,s:string){if(!await this.repo.findAuthorizedSpecialContract(user,s)) throw new AppError("SPECIAL_CONTRACT_NOT_FOUND","Special contract was not found",404); const r=await this.repo.findRule(s); if(!r) throw new AppError("RULE_NOT_FOUND","Rule was not found",404);return r;}
 private async out(r:RuleRow):Promise<RuleResponse>{const versions=(await this.repo.findVersions(r.id)).map(v=>({version:v.version,status:v.status,ruleDefinition:v.ruleDefinition,effectiveFrom:iso(v.effectiveFrom),effectiveTo:iso(v.effectiveTo),approvedBy:v.approvedBy,approvedAt:iso(v.approvedAt),createdAt:v.createdAt.toISOString(),updatedAt:v.updatedAt.toISOString()}));const p=RuleResponseSchema.safeParse({id:r.id,specialContractId:r.specialContractId,versions});if(!p.success)throw new AppError("INTERNAL_SERVER_ERROR","Stored rule data is invalid",500);return p.data;}
 public async get(u:string,s:string){return this.out(await this.rule(u,s));}
 private input(input:unknown){const p=RuleDraftInputSchema.safeParse(input);if(!p.success)throw new AppError("INVALID_REQUEST","Rule draft is invalid",400);return p.data;}
 public async create(u:string,s:string,input:unknown){if(!await this.repo.findAuthorizedSpecialContract(u,s))throw new AppError("SPECIAL_CONTRACT_NOT_FOUND","Special contract was not found",404);if(await this.repo.findRule(s))throw new AppError("RULE_ALREADY_EXISTS","A logical rule already exists",409);const d=this.input(input);return this.out(await this.repo.createRule(s,this.definition(d),d.effectiveFrom??null,d.effectiveTo??null));}
 private definition(d:ReturnType<typeof RuleDraftInputSchema.parse>){return {formula:d.formula,initialScore:d.initialScore,speedingPenalty:d.speedingPenalty,accelerationPenalty:d.accelerationPenalty,brakingPenalty:d.brakingPenalty,minimumDistanceM:d.minimumDistanceM,minimumScore:d.minimumScore,premiumMinimumScore:d.premiumMinimumScore,baseDiscountBps:d.baseDiscountBps,premiumDiscountBps:d.premiumDiscountBps};}
 public async update(u:string,s:string,v:number,input:unknown){const r=await this.rule(u,s);const d=this.input(input);if(!await this.repo.updateDraft(r.id,v,this.definition(d),d.effectiveFrom??null,d.effectiveTo??null)){const old=await this.repo.findVersion(r.id,v);throw new AppError(old?"RULE_NOT_EDITABLE":"RULE_VERSION_NOT_FOUND",old?"Approved rule version is immutable":"Rule version was not found",old?409:404);}return this.out(r);}
 public async approve(u:string,s:string,v:number){const r=await this.rule(u,s);if(!await this.repo.approveDraft(r.id,v,u)){const old=await this.repo.findVersion(r.id,v);throw new AppError(old?"RULE_ALREADY_APPROVED":"RULE_VERSION_NOT_FOUND",old?"Rule version is already approved":"Rule version was not found",old?409:404);}return this.out(r);}
 public async next(u:string,s:string,input:unknown){const r=await this.rule(u,s);const d=this.input(input);await this.repo.createNextDraft(r.id,this.definition(d),d.effectiveFrom??null,d.effectiveTo??null);return this.out(r);}
}
