import type { Pool, PoolClient } from "pg";

export interface RuleVersionRow { version: number; status: "DRAFT" | "APPROVED"; ruleDefinition: unknown; effectiveFrom: Date | null; effectiveTo: Date | null; approvedBy: string | null; approvedAt: Date | null; createdAt: Date; updatedAt: Date; }
export interface RuleRow { id: string; specialContractId: string; }
export interface RuleRepository { findAuthorizedSpecialContract(userId: string, specialContractId: string): Promise<boolean>; findRule(specialContractId: string): Promise<RuleRow | undefined>; findVersions(ruleId: string): Promise<RuleVersionRow[]>; findVersion(ruleId: string, version: number): Promise<RuleVersionRow | undefined>; createRule(specialContractId: string, definition: unknown, from: string | null, to: string | null): Promise<RuleRow>; updateDraft(ruleId: string, version: number, definition: unknown, from: string | null, to: string | null): Promise<RuleVersionRow | undefined>; approveDraft(ruleId: string, version: number, userId: string): Promise<RuleVersionRow | undefined>; createNextDraft(ruleId: string, definition: unknown, from: string | null, to: string | null): Promise<RuleVersionRow>; }
export class PgRuleRepository implements RuleRepository {
 public constructor(private readonly pool: Pool) {}
 public async findAuthorizedSpecialContract(userId:string, specialContractId:string){ const r=await this.pool.query(`SELECT 1 FROM public.special_contracts s JOIN public.insurance_contracts c ON c.id=s.insurance_contract_id JOIN public.insurer_memberships m ON m.insurer_id=c.insurer_id WHERE s.id=$1 AND m.user_id=$2`,[specialContractId,userId]); return (r.rowCount ?? 0)>0; }
 public async findRule(s:string){const r=await this.pool.query<RuleRow>(`SELECT id, special_contract_id AS "specialContractId" FROM public.rules WHERE special_contract_id=$1`,[s]);return r.rows[0];}
 private async versions(q:Pool|PoolClient, sql:string,args:unknown[]){const r=await q.query<RuleVersionRow>(sql,args);return r.rows;}
 public async findVersions(id:string){return this.versions(this.pool,`SELECT version,status,rule_definition AS "ruleDefinition",effective_from AS "effectiveFrom",effective_to AS "effectiveTo",approved_by AS "approvedBy",approved_at AS "approvedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM public.rule_versions WHERE rule_id=$1 ORDER BY version`,[id]);}
 public async findVersion(id:string,v:number){return (await this.findVersions(id)).find(x=>x.version===v);}
 public async createRule(s:string,d:unknown,f:string|null,t:string|null){const c=await this.pool.connect();try{await c.query("BEGIN");const r=await c.query<RuleRow>(`INSERT INTO public.rules(special_contract_id) VALUES($1) RETURNING id,special_contract_id AS "specialContractId"`,[s]);await c.query(`INSERT INTO public.rule_versions(rule_id,version,status,rule_definition,effective_from,effective_to) VALUES($1,1,'DRAFT',$2,$3,$4)`,[r.rows[0].id,d,f,t]);await c.query("COMMIT");return r.rows[0];}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 public async updateDraft(id:string,v:number,d:unknown,f:string|null,t:string|null){return (await this.versions(this.pool,`UPDATE public.rule_versions SET rule_definition=$3,effective_from=$4,effective_to=$5 WHERE rule_id=$1 AND version=$2 AND status='DRAFT' RETURNING version,status,rule_definition AS "ruleDefinition",effective_from AS "effectiveFrom",effective_to AS "effectiveTo",approved_by AS "approvedBy",approved_at AS "approvedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[id,v,d,f,t]))[0];}
 public async approveDraft(id:string,v:number,u:string){return (await this.versions(this.pool,`UPDATE public.rule_versions SET status='APPROVED',approved_by=$3,approved_at=now() WHERE rule_id=$1 AND version=$2 AND status='DRAFT' RETURNING version,status,rule_definition AS "ruleDefinition",effective_from AS "effectiveFrom",effective_to AS "effectiveTo",approved_by AS "approvedBy",approved_at AS "approvedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[id,v,u]))[0];}
 public async createNextDraft(id:string,d:unknown,f:string|null,t:string|null){const c=await this.pool.connect();try{await c.query("BEGIN");const r=await this.versions(c,`INSERT INTO public.rule_versions(rule_id,version,status,rule_definition,effective_from,effective_to) SELECT $1,COALESCE(MAX(version),0)+1,'DRAFT',$2,$3,$4 FROM public.rule_versions WHERE rule_id=$1 RETURNING version,status,rule_definition AS "ruleDefinition",effective_from AS "effectiveFrom",effective_to AS "effectiveTo",approved_by AS "approvedBy",approved_at AS "approvedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[id,d,f,t]);await c.query("COMMIT");return r[0];}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
}
