import { DrivingSessionResponseSchema, RuleSchema, hasZeroGenesisMetrics, type AdapterRuntime, type DrivingSessionResponse, type Trip } from "@drivacy/shared";
import { AppError } from "../errors/app-error.js";
import { toRuleVersionNumber } from "../rule/rule-service.js";
import type { ConfirmedDrivingStateReader } from "./confirmed-state-reader.js";
import { generateTrip, type RandomProvider } from "./driving-generator.js";
import type { DrivingRepository, DrivingSessionRow } from "./driving-repository.js";

const iso=(value:Date|string|null)=>value instanceof Date?value.toISOString():value;
export class DrivingService { public constructor(private readonly repo:DrivingRepository,private readonly runtime:AdapterRuntime,private readonly states:ConfirmedDrivingStateReader,private readonly random?:RandomProvider) {}
  private async response(row:DrivingSessionRow):Promise<DrivingSessionResponse>{const trip:Trip={id:row.tripId,source:"simulated",collectionEnabled:true,datasetSalt:row.datasetSalt,records:await this.repo.records(row.id)};const parsed=DrivingSessionResponseSchema.safeParse({sessionId:row.id,status:row.status,startedAt:iso(row.startedAt),endedAt:iso(row.endedAt),trip});if(!parsed.success)throw new AppError("INTERNAL_SERVER_ERROR","Stored driving session data is invalid",500);return parsed.data;}
  public async start(user:string,input:{insuranceContractId:string;specialContractId:string;evaluationPeriod:string},key:string){const target=await this.repo.findTarget(user,input.insuranceContractId,input.specialContractId,input.evaluationPeriod,this.runtime);if(!target)throw new AppError("DRIVING_SCOPE_NOT_FOUND","Driving scope was not found",404);const existing=await this.repo.findByKey(target.scopeId,key);if(existing)return this.response(existing);if(!target.ruleVersionId)throw new AppError("RULE_NOT_REGISTERED","No chain-confirmed Rule is currently applied",409);if(target.ruleStatus!=="APPROVED"||!target.ruleVersion||!target.ruleId||!target.insurerId||!target.ruleDefinition||!target.ruleHash||!target.chainContractAddress)throw new AppError("RULE_NOT_REGISTERED","Current Rule is not available",409);
    const previous=await this.states.getConfirmedState(target.scopeId);
    // 승인된 Rule의 체인 등록만으로는 최초 운행을 만들 수 없다. Genesis 또는 최신 확정 State가 같은 계약·Runtime·Rule에 묶여 있어야 한다.
    if(!previous||previous.confirmation.execution!=="live"||previous.confirmation.network!==this.runtime.network||previous.confirmation.adapterProfile!==this.runtime.adapterProfile||previous.confirmation.chainContractAddress!==target.chainContractAddress||previous.state.rule.id!==target.ruleId||previous.state.rule.version!==toRuleVersionNumber(target.ruleVersion)||previous.state.rule.ruleHash!==target.ruleHash||previous.state.scope.applicantId!==user||previous.state.scope.contractId!==input.insuranceContractId||previous.state.scope.endorsementId!==input.specialContractId||previous.state.scope.insurerId!==target.insurerId||previous.state.scope.evaluationPeriod.id!==target.evaluationPeriodId||previous.state.version!==previous.state.tripCount||(previous.state.version===0&&!hasZeroGenesisMetrics(previous.state)))throw new AppError("CONFIRMED_STATE_UNAVAILABLE","A matching chain-confirmed state is required before driving",409);
    if(previous.state.version===0&&await this.repo.hasSession(target.scopeId))throw new AppError("CONFIRMED_STATE_UNAVAILABLE","A confirmed state is required for a subsequent driving session",409);
    const rule=RuleSchema.safeParse({id:target.ruleId,version:toRuleVersionNumber(target.ruleVersion),insurerId:target.insurerId,endorsementId:target.specialContractId,...(target.ruleDefinition as object)});if(!rule.success)throw new AppError("INTERNAL_SERVER_ERROR","Stored Rule data is invalid",500);const trip=generateTrip(rule.data,previous.state.totals.distanceM,this.random);const row=await this.repo.createSession({evaluationScopeId:target.scopeId,ruleVersionId:target.ruleVersionId,tripId:trip.id,datasetSalt:trip.datasetSalt,idempotencyKey:key,startedAt:new Date()},trip);return this.response(row);}
  public async get(id:string,user:string){const row=await this.repo.findOwned(id,user);if(!row)throw new AppError("DRIVING_SESSION_NOT_FOUND","Driving session was not found",404);return this.response(row);}
  public async end(id:string,user:string){const row=await this.repo.endOwned(id,user);if(!row)throw new AppError("DRIVING_SESSION_NOT_FOUND","Driving session was not found",404);return this.response(row);}
}
