import type { Pool } from "pg";
import type { AdapterRuntime, Trip } from "@drivacy/shared";

export interface DrivingTarget { scopeId:string; evaluationPeriodId:string; ruleVersionId:string|null; ruleVersion:string|null; ruleStatus:"DRAFT"|"APPROVED"|null; ruleId:string|null; insurerId:string|null; specialContractId:string; ruleDefinition:unknown|null; ruleHash:string|null; chainContractAddress:string|null; }
export interface DrivingSessionRow { id:string; evaluationScopeId:string; ruleVersionId:string; tripId:string; datasetSalt:string; idempotencyKey:string; status:"GENERATED"|"ENDED"; startedAt:Date|string; endedAt:Date|string|null; }
export interface NewDrivingSession { evaluationScopeId:string; ruleVersionId:string; tripId:string; datasetSalt:string; idempotencyKey:string; generationStateCommitment:string; startedAt:Date|string; }
export interface DrivingRepository { findTarget(user:string, contract:string, special:string, period:string, runtime:AdapterRuntime):Promise<DrivingTarget|undefined>; findByKey(scope:string,key:string):Promise<DrivingSessionRow|undefined>; createSession(session:NewDrivingSession,trip:Trip):Promise<DrivingSessionRow|undefined>; findOwned(id:string,user:string):Promise<DrivingSessionRow|undefined>; endOwned(id:string,user:string):Promise<DrivingSessionRow|undefined>; records(id:string):Promise<Trip["records"]>; }
export class PgDrivingRepository implements DrivingRepository { public constructor(private readonly pool:Pool) {}
  public async findTarget(user:string,contract:string,special:string,period:string,runtime:AdapterRuntime){const r=await this.pool.query<DrivingTarget>(`SELECT es.id AS "scopeId",es.evaluation_period_id AS "evaluationPeriodId",d.current_rule_version_id AS "ruleVersionId",rv.version AS "ruleVersion",rv.status AS "ruleStatus",rules.id AS "ruleId",c.insurer_id AS "insurerId",s.id AS "specialContractId",rv.rule_definition AS "ruleDefinition",rr.rule_hash AS "ruleHash",d.chain_contract_address AS "chainContractAddress" FROM public.evaluation_scopes es JOIN public.insurance_contracts c ON c.id=es.insurance_contract_id AND c.owner_user_id=$1 JOIN public.special_contracts s ON s.id=es.special_contract_id AND s.insurance_contract_id=c.id JOIN public.special_contract_selections sel ON sel.insurance_contract_id=c.id AND sel.special_contract_id=s.id LEFT JOIN public.chain_scope_deployments d ON d.evaluation_scope_id=es.id AND d.network=$5 AND d.adapter_profile=$6 LEFT JOIN public.rule_versions rv ON rv.id=d.current_rule_version_id LEFT JOIN public.rules rules ON rules.id=rv.rule_id LEFT JOIN public.rule_registrations rr ON rr.chain_scope_deployment_id=d.id AND rr.rule_version_id=d.current_rule_version_id WHERE c.id=$2 AND s.id=$3 AND es.evaluation_period_id=$4`,[user,contract,special,period,runtime.network,runtime.adapterProfile]);return r.rows[0];}
  public async findByKey(scope:string,key:string){const r=await this.pool.query<DrivingSessionRow>(`SELECT id,evaluation_scope_id AS "evaluationScopeId",rule_version_id AS "ruleVersionId",trip_id AS "tripId",dataset_salt AS "datasetSalt",idempotency_key AS "idempotencyKey",status,started_at AS "startedAt",ended_at AS "endedAt" FROM public.driving_sessions WHERE evaluation_scope_id=$1 AND idempotency_key=$2`,[scope,key]);return r.rows[0];}
  public async createSession(s:NewDrivingSession,trip:Trip):Promise<DrivingSessionRow|undefined>{const c=await this.pool.connect();try{await c.query("BEGIN");
    // 애플리케이션 선조회만으로는 동시 요청을 안전하게 차단할 수 없으므로, 현재 State 확인과 Session 생성을 DB에서 원자적으로 처리한다.
    // 부분 UNIQUE 인덱스가 하나의 Confirmed State가 두 번 소비되는 것을 막는다.
    const created=await c.query<DrivingSessionRow>(`INSERT INTO public.driving_sessions(evaluation_scope_id,rule_version_id,trip_id,dataset_salt,idempotency_key,generation_state_commitment,status)
      SELECT $1,$2,$3,$4,$5,$6,'GENERATED'
        FROM public.evaluation_scopes es
        JOIN public.chain_states cs ON cs.owner_user_id=es.owner_user_id
          AND cs.insurance_contract_id=es.insurance_contract_id
          AND cs.special_contract_id=es.special_contract_id
          AND cs.confirmed_state #>> '{state,scope,evaluationPeriod,id}'=es.evaluation_period_id
       WHERE es.id=$1 AND cs.state_commitment=$6
      ON CONFLICT DO NOTHING
      RETURNING id,evaluation_scope_id AS "evaluationScopeId",rule_version_id AS "ruleVersionId",trip_id AS "tripId",dataset_salt AS "datasetSalt",idempotency_key AS "idempotencyKey",status,started_at AS "startedAt",ended_at AS "endedAt"`,[s.evaluationScopeId,s.ruleVersionId,s.tripId,s.datasetSalt,s.idempotencyKey,s.generationStateCommitment]);
    const row=created.rows[0];if(!row){const existing=await c.query<DrivingSessionRow>(`SELECT id,evaluation_scope_id AS "evaluationScopeId",rule_version_id AS "ruleVersionId",trip_id AS "tripId",dataset_salt AS "datasetSalt",idempotency_key AS "idempotencyKey",status,started_at AS "startedAt",ended_at AS "endedAt" FROM public.driving_sessions WHERE evaluation_scope_id=$1 AND idempotency_key=$2`,[s.evaluationScopeId,s.idempotencyKey]);await c.query("COMMIT");return existing.rows[0];}const result=row;for(const x of trip.records)await c.query(`INSERT INTO public.driving_segments(driving_session_id,segment_index,distance_m,duration_seconds,speeding_count,acceleration_count,braking_count) VALUES($1,$2,$3,$4,$5,$6,$7)`,[result.id,x.index,x.distanceM,x.durationSeconds,x.speedingCount,x.accelerationCount,x.brakingCount]);await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
  public async findOwned(id:string,user:string){const r=await this.pool.query<DrivingSessionRow>(`SELECT ds.id,ds.evaluation_scope_id AS "evaluationScopeId",ds.rule_version_id AS "ruleVersionId",ds.trip_id AS "tripId",ds.dataset_salt AS "datasetSalt",ds.idempotency_key AS "idempotencyKey",ds.status,ds.started_at AS "startedAt",ds.ended_at AS "endedAt" FROM public.driving_sessions ds JOIN public.evaluation_scopes es ON es.id=ds.evaluation_scope_id AND es.owner_user_id=$2 WHERE ds.id=$1`,[id,user]);return r.rows[0];}
  public async endOwned(id:string,user:string){const r=await this.pool.query<DrivingSessionRow>(`UPDATE public.driving_sessions ds SET status='ENDED',ended_at=COALESCE(ds.ended_at,now()) FROM public.evaluation_scopes es WHERE ds.id=$1 AND ds.evaluation_scope_id=es.id AND es.owner_user_id=$2 RETURNING ds.id,ds.evaluation_scope_id AS "evaluationScopeId",ds.rule_version_id AS "ruleVersionId",ds.trip_id AS "tripId",ds.dataset_salt AS "datasetSalt",ds.idempotency_key AS "idempotencyKey",ds.status,ds.started_at AS "startedAt",ds.ended_at AS "endedAt"`,[id,user]);return r.rows[0];}
  public async records(id:string){const r=await this.pool.query<{index:number;distanceM:string;durationSeconds:string;speedingCount:string;accelerationCount:string;brakingCount:string}>(`SELECT segment_index AS index,distance_m AS "distanceM",duration_seconds AS "durationSeconds",speeding_count AS "speedingCount",acceleration_count AS "accelerationCount",braking_count AS "brakingCount" FROM public.driving_segments WHERE driving_session_id=$1 ORDER BY segment_index`,[id]);return r.rows.map(x=>({index:x.index,distanceM:uint(x.distanceM),durationSeconds:uint(x.durationSeconds),speedingCount:uint(x.speedingCount),accelerationCount:uint(x.accelerationCount),brakingCount:uint(x.brakingCount)}));}
}
const uint=(value:string)=>{const n=Number(value);if(!Number.isInteger(n)||n<0||n>0xffff_ffff)throw new Error("Stored driving segment metric is invalid");return n;};
